config/routes.rb
Rails.application.routes.draw do

  resources :doctors, only: :show
  resources :doctor_patients, only: :destroy
  resources :patients, only: :index
  resources :hospitals, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :hospital
  has_many :doctor_patients
  has_many :patients, through: :doctor_patients

  def hospital_name
    hospital.name
  end

  def find_join_id(pat)
    doctor_patients.where(doctor_patients: {patient_id: pat.id}).pluck(:id).first
  end
end

app/models/doctor_patient.rb
class DoctorPatient < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :doctors
  has_many :doctor_patients, through: :doctors
  has_many :patients, through: :doctor_patients

  def doctors_patient_count
    doctors.joins(:patients)
    .select('doctors.*, count(patients) as num_patients')
    .group(:id)
    .order(num_patients: :desc)
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :doctor_patients
  has_many :doctors, through: :doctor_patients

  def self.list
    where('patients.age >= 18').order(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctor_patients_controller.rb
class DoctorPatientsController < ApplicationController

  def destroy
    doctor_patient = DoctorPatient.find(params[:id])
    doctor = Doctor.find(doctor_patient.doctor.id)
    doctor_patient.destroy
    redirect_to doctor_path(doctor)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def show
    @doctor = Doctor.find(params[:id])
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

  def show
    @hospital = Hospital.find(params[:id])
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @patients = Patient.list
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/doctors/show.html.erb
<h1>Doctor: <%= @doctor.name %></h1>
<h2>Specialty: <%= @doctor.specialty %></h2>
<h2>University Attended: <%= @doctor.university %></h2>
<h2>Hospital Attending: <%= @doctor.hospital_name %>

<h3>Patients: 
<ul>
<% @doctor.patients.each do |patient| %>
  <li id="patient_<%=patient.id %>">
    <%= patient.name %>
    <%= button_to "Remove Patient", doctor_patient_path(@doctor.find_join_id(patient)), method: :delete %>
  </li>
    <br>
<% end %>
</ul>

app/views/hospitals/show.html.erb
<h1><%= @hospital.name %></h1>

<h3>Doctors on Staff:</h3>

<% @hospital.doctors_patient_count.each do |doctor| %>
  <div id="doctor_<%=doctor.id%>">
    <p>Doctor: <%= doctor.name %></p>
    <p>Number of Patients: <%= doctor.num_patients %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseNew</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/index.html.erb
<h1>Patients Index </h1>

<ul>
<% @patients.each do |patient| %>
  <li><%= patient.name %></li>
<% end %>
</ul>